### ISSUE TITLE
Starter selection needs to be consistent

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/metronome-sapphire#6]
Currently, the starter selector doesn't show the starter you get, and also may not create a pokedex entry for the starter you get.

**Comment by m4-used-rollout** [comment]
This might be difficult to do since starters are static in ROM. Having the game choose different random starters each time is tough.

Maybe skip the entire starter selection sequence?

**Comment by aaaaaa123456789** [comment]
Define "static"?

**Comment by m4-used-rollout** [comment]
I mean the starter table is stored in ROM not RAM. It's a static const. The game can't edit it live.

**Comment by aaaaaa123456789** [comment]
That should be an easy fix.

**Comment by m4-used-rollout** [comment]
Fixed by 1ea5156d205bbfd7157f5525d9f09cf6146eadd7
