### ISSUE TITLE
Wally's Catching Tutorial can Softlock

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/metronome-sapphire#9]
If Wally's mon faints, choosing to send out another sends out a bad egg and softlocks.

We need to either:

- Make Wally throw the ball turn 1 (preferred)
- Make Wally's mon fainting end the tutorial
- Make Wally's mon invincible
- Spawn a Level 10 Ralts (boring)

**Comment by m4-used-rollout** [comment]
This bug might not exist. Apparently it was reported based on the behavior of other romhacks.

Here's a [video](https://cdn.discordapp.com/attachments/444452437139521536/551838785588035604/No_crash.mov) showing how Metronome Sapphire behaves.

**Comment by PikalaxALT** [comment]
Commits cc4b9d67bd601639841e78d7d38b827d3a676302 and 0f5bc96f5344a1a0726ca07d40a9eefbe3fc523c resolve this issue.
